# Generated by Django 5.1 on 2024-09-04 07:33

import apps.tasks.choices.statuses
import apps.tasks.utils.set_end_of_month
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=apps.tasks.choices.statuses.Statuses.choices, default=apps.tasks.choices.statuses.Statuses['NEW'], max_length=15)),
                ('priority', models.SmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(default=apps.tasks.utils.set_end_of_month.calculate_end_of_month)),
            ],
            options={
                'ordering': ['-deadline'],
            },
        ),
    ]
